version: "3.8"

services:
  data_science:
    build: .
    working_dir: /home/src/
    tty: true
    volumes:
      - ./:/home/src/
    ports:
      - "8889:8889"
    networks:
      - localbound
networks:
  localbound:
    external: true
